### Dataframes

In [2]:
import numpy as np
import pandas as pd

In [3]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

### Creating dataframe by passing a dictionary

In [6]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [20]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -1.745319 -0.665276 -0.412963 -0.143945
2013-01-02  0.434241 -0.834588  0.881814 -0.346833
2013-01-03 -0.163079  0.469482  0.440374 -0.584764
2013-01-04  0.488072  0.504117  0.143680 -0.394643
2013-01-05 -2.091038 -1.969294 -1.698797  1.348180
2013-01-06  0.486325 -1.732099 -0.216367 -0.444474

### Viewing Data

In [21]:

df.head()

                   A         B         C         D
2013-01-01 -1.745319 -0.665276 -0.412963 -0.143945
2013-01-02  0.434241 -0.834588  0.881814 -0.346833
2013-01-03 -0.163079  0.469482  0.440374 -0.584764
2013-01-04  0.488072  0.504117  0.143680 -0.394643
2013-01-05 -2.091038 -1.969294 -1.698797  1.348180

In [22]:
df.head(2)

                   A         B         C         D
2013-01-01 -1.745319 -0.665276 -0.412963 -0.143945
2013-01-02  0.434241 -0.834588  0.881814 -0.346833

In [23]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

We can check the columns of a dataframe

In [24]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

We can also return a NumPY representation

In [25]:
df.to_numpy()

array([[-1.74531881, -0.66527552, -0.41296262, -0.14394521],
       [ 0.43424128, -0.83458815,  0.88181443, -0.34683332],
       [-0.16307939,  0.46948218,  0.44037423, -0.58476359],
       [ 0.48807228,  0.50411674,  0.14367989, -0.39464282],
       [-2.09103818, -1.96929398, -1.69879651,  1.34818034],
       [ 0.4863245 , -1.73209896, -0.21636694, -0.44447405]])

Showing a quck view of the data

In [26]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.431800 -0.704610 -0.143710 -0.094413
std    1.182350  1.050058  0.891237  0.721161
min   -2.091038 -1.969294 -1.698797 -0.584764
25%   -1.349759 -1.507721 -0.363814 -0.432016
50%    0.135581 -0.749932 -0.036344 -0.370738
75%    0.473304  0.185793  0.366201 -0.194667
max    0.488072  0.504117  0.881814  1.348180

Selecting data

In [27]:
df["A"]

2013-01-01   -1.745319
2013-01-02    0.434241
2013-01-03   -0.163079
2013-01-04    0.488072
2013-01-05   -2.091038
2013-01-06    0.486325
Freq: D, Name: A, dtype: float64

In [28]:
df[["A","B"]]

                   A         B
2013-01-01 -1.745319 -0.665276
2013-01-02  0.434241 -0.834588
2013-01-03 -0.163079  0.469482
2013-01-04  0.488072  0.504117
2013-01-05 -2.091038 -1.969294
2013-01-06  0.486325 -1.732099

### Missing data

In [29]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])

df1.loc[dates[0] : dates[1], "E"] = 1

In [30]:
df1.dropna(how="any")

                   A         B         C         D    E
2013-01-01 -1.745319 -0.665276 -0.412963 -0.143945  1.0
2013-01-02  0.434241 -0.834588  0.881814 -0.346833  1.0

finds if they are nan or not

In [32]:
pd.isna(df1)

                A      B      C      D      E
2013-01-01  False  False  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-04  False  False  False  False   True